/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aacencoder_JNIAACEncode */

#ifndef _Included_com_aacencoder_JNIAACEncode
#define _Included_com_aacencoder_JNIAACEncode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aacencoder_JNIAACEncode
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aacencoder_JNIAACEncode_init
  (JNIEnv *, jobject, jint);
/*
 * Class:     com_aacencoder_JNIAACEncode
 * Method:    g711Ainit
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_com_aacencoder_JNIAACEncode_g711Ainit
//  (JNIEnv *, jobject);

/*
 * Class:     com_aacencoder_JNIAACEncode
 * Method:    g711Uinit
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_com_aacencoder_JNIAACEncode_g711Uinit
//  (JNIEnv *, jobject);

/*
 * Class:     com_aacencoder_JNIAACEncode
 * Method:    release
 * Signature: ()V
 */
//JNIEXPORT void JNICALL Java_com_aacencoder_JNIAACEncode_release
//  (JNIEnv *, jobject);

/*
 * Class:     com_aacencoder_JNIAACEncode
 * Method:    encode
 * Signature: ([BI[BI)[B
 */
//JNIEXPORT jbyteArray JNICALL Java_com_aacencoder_JNIAACEncode_encode
//  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_aacencoder_JNIAACEncode
 * Method:    encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jint JNICALL Java_com_aacencoder_JNIAACEncode_encode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
